# Change these first
owner: andrew-forster
repo: upptime # The name of this repository

sites:
  - name: Personal Site
    url: https://andrewjf.com
  - name: Blog Site
    url: https://blog.andrewjf.com
  - name: Alchemy Analytix
    url: https://alchemyanalytix.com

status-website:
  theme: dark
  cname: status.andrewjf.com
  logoUrl: https://andrewjf.com/assets/images/me.jpg
  name: Upptime
  introTitle: "This site is used to track up-time and down-time for website created by Andrew."
  introMessage: The status of my sites are listed below
  navbar:
    - title: Uptime Repo
      href: https://github.com/andrew-forster/upptime
    - title: Personal Site
      url: https://andrewjf.com
    - title: Blog Site
      url: https://blog.andrewjf.com
    - title: Alchemy Analytix
      url: https://alchemyanalytix.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
